version: 0.0
os: linux
files:
  - source: /  # Root of your repository (where server.js, package.json, etc. are located)
    destination: /home/ubuntu  # Where the files will be placed on the EC2 instance

hooks:
  AfterInstall:
    - location: afterinstall.sh  # Install dependencies after files are copied
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh  # Start the Node.js app
      timeout: 100
