version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Use Node.js 16
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install  # Install the dependencies in package.json
  build:
    commands:
      - echo "Build started on $(date)"  # Use $(date) to get the current date
      - echo "Compiling the Node.js code if needed"  # Fixed the echo statement without parentheses
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Storing build artifacts in S3"

artifacts:
  files:
    - '**/*'  # Include all files (your server code, static files, etc.)
  exclude-files:
    - '**/node_modules/**/*'  # Exclude node_modules to reduce artifact size
